<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class A1UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('a1_users')->delete();
        
        \DB::table('a1_users')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'Admin',
                'email' => 'admin@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$MHJ9PzcQqYtedK.l.lw33.aIvDcsCDGmF72kkObbe8eM1qMBGSu5y',
                'avatar' => 'avatar.png',
                'messenger_color' => '#2180f3',
                'dark_mode' => 0,
                'active_status' => 0,
                'contact' => '01900000000',
                'type' => 'admin',
                'location' => 'Dhaka',
                'gender' => 'male',
                'birthdate' => '1995-10-01',
                'district_id' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-12-11 09:11:43',
                'updated_at' => '2020-12-18 16:10:07',
            ),
            1 => 
            array (
                'id' => 13,
                'name' => 'SAKIB SIKDER',
                'email' => 'juralacuity@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$bDraIZGVH9SKRHS1ex1vseyg7aR312zRKVNnWnkhgooXQvUWB/zHO',
                'avatar' => '05325671-40f4-4014-948e-c9cf08f8b337.jpg',
                'messenger_color' => '#2180f3',
                'dark_mode' => 0,
                'active_status' => 0,
                'contact' => '01707108000',
                'type' => 'lawyer',
                'location' => 'Banani',
                'gender' => 'male',
                'birthdate' => '1990-10-10',
                'district_id' => 1,
                'remember_token' => NULL,
                'created_at' => '2020-12-24 17:13:21',
                'updated_at' => '2020-12-24 18:04:44',
            ),
            2 => 
            array (
                'id' => 14,
                'name' => 'AFRIN AHMED',
                'email' => 'info@juralacuity.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$hrGaM5T4.LiPUfK0g7G2VewkTyI1R6GvQsnLiraeqrDYvzeMtoO1K',
                'avatar' => '6b01f6c7-07ef-412a-b631-1e563a632873.jpg',
                'messenger_color' => '#2180f3',
                'dark_mode' => 0,
                'active_status' => 0,
                'contact' => '01707108000',
                'type' => 'lawyer',
                'location' => 'majar road',
                'gender' => 'female',
                'birthdate' => '1971-05-11',
                'district_id' => 45,
                'remember_token' => NULL,
                'created_at' => '2020-12-24 17:41:14',
                'updated_at' => '2020-12-24 18:12:26',
            ),
            3 => 
            array (
                'id' => 15,
                'name' => 'S M SAIFULLAH RAHMAN',
                'email' => 'juralacuity20@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$6ILs5fAF3y1.gzrvwIcANuRSYPLGSQSxucXliRjYnzVi5xiuMhsGm',
                'avatar' => 'bf9531e8-6dc3-45de-a0c1-8d3ba3cf2c63.JPG',
                'messenger_color' => '#2180f3',
                'dark_mode' => 0,
                'active_status' => 0,
                'contact' => '01707108000',
                'type' => 'lawyer',
                'location' => 'hatem ali road',
                'gender' => 'male',
                'birthdate' => '1995-09-12',
                'district_id' => 55,
                'remember_token' => NULL,
                'created_at' => '2020-12-24 17:46:04',
                'updated_at' => '2020-12-24 17:54:36',
            ),
            4 => 
            array (
                'id' => 16,
                'name' => 'MD. SHAHABUDDIN MOLLA',
                'email' => 'juralacuity50@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$THuHvI/nJiMVooggXPCn1uxfTlOEoP69e4spH8L.58DTDex0wpIVi',
                'avatar' => 'f18fe728-a6a5-43b6-88ab-16ce8f3a367f.jpg',
                'messenger_color' => '#2180f3',
                'dark_mode' => 0,
                'active_status' => 0,
                'contact' => '8801707108000',
                'type' => 'lawyer',
                'location' => 'bonarpara',
                'gender' => 'male',
                'birthdate' => '1975-06-22',
                'district_id' => 30,
                'remember_token' => NULL,
                'created_at' => '2020-12-24 18:18:21',
                'updated_at' => '2020-12-24 18:22:11',
            ),
            5 => 
            array (
                'id' => 17,
                'name' => 'SYED AZIZUL IQBAL',
                'email' => 'juralacuity55@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$f61qLTgNy/mLW.LrVZo9B.nlCO6sr5obvhda02LD2Y3sqcyaSVnEC',
                'avatar' => '1920005f-be5b-4afa-8b0b-87f7f6576de3.jpg',
                'messenger_color' => '#2180f3',
                'dark_mode' => 0,
                'active_status' => 0,
                'contact' => '8801707108000',
                'type' => 'lawyer',
                'location' => 'lalbagh',
                'gender' => 'male',
                'birthdate' => '1995-03-08',
                'district_id' => 1,
                'remember_token' => NULL,
                'created_at' => '2020-12-24 18:27:06',
                'updated_at' => '2020-12-24 18:32:37',
            ),
            6 => 
            array (
                'id' => 18,
                'name' => 'MD. RASEL MIAH',
                'email' => 'info00@juralacuity.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$NezI03tNqFIF8W5Ot7Nem.OZf8pQzuIVFPW/4pBAHvio9UM84LcE6',
                'avatar' => 'd791bcf0-666b-45d2-8898-bb5dd1b0d210.jpg',
                'messenger_color' => '#2180f3',
                'dark_mode' => 0,
                'active_status' => 0,
                'contact' => '01707108000',
                'type' => 'lawyer',
                'location' => 'poliaha',
                'gender' => 'male',
                'birthdate' => '1991-01-14',
                'district_id' => 5,
                'remember_token' => NULL,
                'created_at' => '2020-12-24 18:37:19',
                'updated_at' => '2020-12-24 18:46:05',
            ),
            7 => 
            array (
                'id' => 19,
                'name' => 'ASHRAFUN NAHAR',
                'email' => 'info22@juralacuity.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$JE0t19RC6J2XjJGcs.xYAu22HRG.Kumc9VVrFYiRRhNA6acYrhq0a',
                'avatar' => 'e4b26236-3966-4ec2-9a41-c9a485a9bf88.jpg',
                'messenger_color' => '#2180f3',
                'dark_mode' => 0,
                'active_status' => 0,
                'contact' => '8801707108000',
                'type' => 'lawyer',
                'location' => 'mirpur',
                'gender' => 'female',
                'birthdate' => '1992-06-26',
                'district_id' => 1,
                'remember_token' => NULL,
                'created_at' => '2020-12-24 18:50:26',
                'updated_at' => '2020-12-24 18:53:31',
            ),
            8 => 
            array (
                'id' => 20,
                'name' => 'MR. MUJIBUL HAQUE',
                'email' => 'juralacuity110@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$CyL7rbDteO5JXjdyXfHWxeMyuv2ksY6XYHi7Gtt18Vpcvsd76xzOC',
                'avatar' => 'f3a9234f-05cb-4be7-b479-b6e4e3dde1fd.jpg',
                'messenger_color' => '#2180f3',
                'dark_mode' => 0,
                'active_status' => 0,
                'contact' => '8801707108000',
                'type' => 'lawyer',
                'location' => 'alekanda',
                'gender' => 'male',
                'birthdate' => '1974-07-03',
                'district_id' => 55,
                'remember_token' => NULL,
                'created_at' => '2020-12-24 18:58:05',
                'updated_at' => '2020-12-24 19:02:31',
            ),
            9 => 
            array (
                'id' => 21,
                'name' => 'Shajib Mahmood Alam',
                'email' => 'info@bdlplaw.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$ptV4D5AwGGsBpEZT/NxhhOXE1ViW6WqWnCwK38VK3XNhPmfWXbULi',
                'avatar' => 'cbbeb0a5-74b9-4d1e-9126-d4402d577b65.jpg',
                'messenger_color' => '#2180f3',
                'dark_mode' => 0,
                'active_status' => 0,
                'contact' => '01714404050',
                'type' => 'lawyer',
                'location' => 'uttra',
                'gender' => 'male',
                'birthdate' => '1990-01-22',
                'district_id' => 1,
                'remember_token' => NULL,
                'created_at' => '2020-12-24 19:07:41',
                'updated_at' => '2020-12-24 19:10:33',
            ),
            10 => 
            array (
                'id' => 22,
                'name' => 'Md Rafinur Rahman',
                'email' => 'info1@bdlplaw.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$oh6A5hCkPZ3r.stTCfSL2e3UZLYXzbNEmW1mtnH4hOcw020Ut1Q7G',
                'avatar' => '20bca83b-9ffc-4a6d-b71c-49f5dbb594e6.jpg',
                'messenger_color' => '#2180f3',
                'dark_mode' => 0,
                'active_status' => 0,
                'contact' => '01714404050',
                'type' => 'lawyer',
                'location' => 'Baridhara DOHS',
                'gender' => 'male',
                'birthdate' => '1987-05-24',
                'district_id' => 1,
                'remember_token' => NULL,
                'created_at' => '2020-12-24 19:30:20',
                'updated_at' => '2020-12-24 19:35:27',
            ),
            11 => 
            array (
                'id' => 23,
                'name' => 'TAJUL ISLAM',
                'email' => 'tajulislam@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$6OymT11kq6Zpq8opLIB92OqDAoG5QEx2gMZ8lSONjUckCeIIn6E8i',
                'avatar' => 'avatar.png',
                'messenger_color' => '#2180f3',
                'dark_mode' => 0,
                'active_status' => 0,
                'contact' => '11111111111111',
                'type' => 'client',
                'location' => 'Medical Road',
                'gender' => 'male',
                'birthdate' => '1992-09-09',
                'district_id' => 54,
                'remember_token' => NULL,
                'created_at' => '2020-12-25 07:06:11',
                'updated_at' => '2020-12-25 07:06:11',
            ),
            12 => 
            array (
                'id' => 24,
                'name' => 'Mehedi hasan',
                'email' => 'mehedihasan221@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$O6xMdxZ7H3RJ63SMww0S6uT5SDDAFNEzb03WT4GiXM6f4ZIP7t3V6',
                'avatar' => 'avatar.png',
                'messenger_color' => '#2180f3',
                'dark_mode' => 0,
                'active_status' => 0,
                'contact' => '01746509698',
                'type' => 'client',
                'location' => 'polashi',
                'gender' => 'male',
                'birthdate' => '1999-06-20',
                'district_id' => 1,
                'remember_token' => NULL,
                'created_at' => '2020-12-25 07:29:14',
                'updated_at' => '2020-12-25 07:29:14',
            ),
            13 => 
            array (
                'id' => 25,
                'name' => 'Nishat Tasnim',
                'email' => 'tasnim005@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$f4DLqgipGdQtLmedKhgUPueLVY3ypLKjGHb0TELxvaWTmiUf2U6Xa',
                'avatar' => 'avatar.png',
                'messenger_color' => '#2180f3',
                'dark_mode' => 0,
                'active_status' => 0,
                'contact' => '01750151515',
                'type' => 'client',
                'location' => 'fulbari',
                'gender' => 'female',
                'birthdate' => '1991-12-12',
                'district_id' => 29,
                'remember_token' => NULL,
                'created_at' => '2020-12-25 07:33:50',
                'updated_at' => '2020-12-25 07:33:50',
            ),
            14 => 
            array (
                'id' => 26,
                'name' => 'Suraiya Parvin',
                'email' => 'suraiyaparvinprity00@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$jgov4p.WFUpS0spbT1JB9eiIKjaM7i12Z2K7wbJ8QRZDtYCnnCM0O',
                'avatar' => 'avatar.png',
                'messenger_color' => '#2180f3',
                'dark_mode' => 0,
                'active_status' => 0,
                'contact' => '01575522552',
                'type' => 'client',
                'location' => 'lalbagh',
                'gender' => 'female',
                'birthdate' => '2000-08-19',
                'district_id' => 1,
                'remember_token' => NULL,
                'created_at' => '2020-12-25 08:00:46',
                'updated_at' => '2020-12-25 08:00:46',
            ),
            15 => 
            array (
                'id' => 27,
                'name' => 'Shams Al Rifat',
                'email' => 'shamsal94@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$ZBhDhHTxc.peOWex7uerLe2xNouHOwMNXHlNt8zCYnHLD3jYqCn8a',
                'avatar' => 'avatar.png',
                'messenger_color' => '#2180f3',
                'dark_mode' => 0,
                'active_status' => 0,
                'contact' => '01735453509',
                'type' => 'client',
                'location' => 'mirpur2',
                'gender' => 'male',
                'birthdate' => '1994-01-19',
                'district_id' => 1,
                'remember_token' => NULL,
                'created_at' => '2020-12-25 08:04:52',
                'updated_at' => '2020-12-25 08:04:52',
            ),
            16 => 
            array (
                'id' => 28,
                'name' => 'Nusaiba Binte',
                'email' => 'binte0090@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$6bprcYIJs8ZZSRr0zRxn1.8qylDgPfK37Fo6knfl8u1ZN6ODVdZ8i',
                'avatar' => 'avatar.png',
                'messenger_color' => '#2180f3',
                'dark_mode' => 0,
                'active_status' => 0,
                'contact' => '01950000102',
                'type' => 'client',
                'location' => 'police fari',
                'gender' => 'female',
                'birthdate' => '1990-09-04',
                'district_id' => 5,
                'remember_token' => NULL,
                'created_at' => '2020-12-25 08:12:45',
                'updated_at' => '2020-12-25 08:12:45',
            ),
            17 => 
            array (
                'id' => 29,
                'name' => 'Khaleda Binte',
                'email' => 'binte.khaleda12@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$7R5S.XQJlIRETHTIv8FwTeE1yhk7x75FGEIWCS40YSxCvKOV96rmy',
                'avatar' => 'avatar.png',
                'messenger_color' => '#2180f3',
                'dark_mode' => 0,
                'active_status' => 0,
                'contact' => '01521425134',
                'type' => 'client',
                'location' => 'Gulshan',
                'gender' => 'female',
                'birthdate' => '1999-09-09',
                'district_id' => 1,
                'remember_token' => NULL,
                'created_at' => '2020-12-25 08:53:57',
                'updated_at' => '2020-12-25 08:53:57',
            ),
            18 => 
            array (
                'id' => 30,
                'name' => 'Fakirul Haque',
                'email' => 'fakir@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$de0.rQ2JZVBQjd9P9PqH/eFFO1v5X7o86Mhd64cOPVsFiS7fGJ9bK',
                'avatar' => 'avatar.png',
                'messenger_color' => '#2180f3',
                'dark_mode' => 0,
                'active_status' => 0,
                'contact' => '01542635142',
                'type' => 'client',
                'location' => 'beach road',
                'gender' => 'male',
                'birthdate' => '1999-09-09',
                'district_id' => 23,
                'remember_token' => NULL,
                'created_at' => '2020-12-25 09:02:22',
                'updated_at' => '2020-12-25 09:02:22',
            ),
        ));
        
        
    }
}