<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class C4EducationsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('c4_educations')->delete();
        
        \DB::table('c4_educations')->insert(array (
            0 => 
            array (
                'id' => 1,
                'user_id' => 13,
                'ssc_year' => NULL,
                'ssc_result' => NULL,
                'ssc_board_id' => NULL,
                'hsc_year' => NULL,
                'hsc_result' => NULL,
                'hsc_board_id' => NULL,
                'degree_year' => 2007,
                'degree_category_id' => 23,
                'uni' => 'City University of London',
                'sub' => 'LL.M',
                'degree_result' => 3.94,
                'created_at' => '2020-12-24 17:13:21',
                'updated_at' => '2020-12-24 18:04:44',
            ),
            1 => 
            array (
                'id' => 2,
                'user_id' => 14,
                'ssc_year' => NULL,
                'ssc_result' => NULL,
                'ssc_board_id' => NULL,
                'hsc_year' => NULL,
                'hsc_result' => NULL,
                'hsc_board_id' => NULL,
                'degree_year' => NULL,
                'degree_category_id' => NULL,
                'uni' => NULL,
                'sub' => NULL,
                'degree_result' => NULL,
                'created_at' => '2020-12-24 17:41:14',
                'updated_at' => '2020-12-24 17:41:14',
            ),
            2 => 
            array (
                'id' => 3,
                'user_id' => 15,
                'ssc_year' => NULL,
                'ssc_result' => NULL,
                'ssc_board_id' => NULL,
                'hsc_year' => NULL,
                'hsc_result' => NULL,
                'hsc_board_id' => NULL,
                'degree_year' => 2020,
                'degree_category_id' => 13,
                'uni' => 'University of London',
                'sub' => 'LLB',
                'degree_result' => 3.5,
                'created_at' => '2020-12-24 17:46:04',
                'updated_at' => '2020-12-24 17:54:37',
            ),
            3 => 
            array (
                'id' => 4,
                'user_id' => 16,
                'ssc_year' => NULL,
                'ssc_result' => NULL,
                'ssc_board_id' => NULL,
                'hsc_year' => NULL,
                'hsc_result' => NULL,
                'hsc_board_id' => NULL,
                'degree_year' => 2012,
                'degree_category_id' => 13,
                'uni' => 'Uttara University',
                'sub' => 'LL.B',
                'degree_result' => 3.23,
                'created_at' => '2020-12-24 18:18:21',
                'updated_at' => '2020-12-24 18:22:11',
            ),
            4 => 
            array (
                'id' => 5,
                'user_id' => 17,
                'ssc_year' => NULL,
                'ssc_result' => NULL,
                'ssc_board_id' => NULL,
                'hsc_year' => NULL,
                'hsc_result' => NULL,
                'hsc_board_id' => NULL,
                'degree_year' => 2019,
                'degree_category_id' => 23,
                'uni' => 'university of dhaka',
                'sub' => 'LL.M',
                'degree_result' => 3.83,
                'created_at' => '2020-12-24 18:27:06',
                'updated_at' => '2020-12-24 18:32:37',
            ),
            5 => 
            array (
                'id' => 6,
                'user_id' => 18,
                'ssc_year' => NULL,
                'ssc_result' => NULL,
                'ssc_board_id' => NULL,
                'hsc_year' => NULL,
                'hsc_result' => NULL,
                'hsc_board_id' => NULL,
                'degree_year' => 2015,
                'degree_category_id' => 23,
                'uni' => 'agricultural university',
                'sub' => 'LL.M',
                'degree_result' => 3.11,
                'created_at' => '2020-12-24 18:37:19',
                'updated_at' => '2020-12-24 18:46:05',
            ),
            6 => 
            array (
                'id' => 7,
                'user_id' => 19,
                'ssc_year' => NULL,
                'ssc_result' => NULL,
                'ssc_board_id' => NULL,
                'hsc_year' => NULL,
                'hsc_result' => NULL,
                'hsc_board_id' => NULL,
                'degree_year' => 2014,
                'degree_category_id' => 23,
                'uni' => 'BUBT',
                'sub' => 'LL.M',
                'degree_result' => 3.0,
                'created_at' => '2020-12-24 18:50:26',
                'updated_at' => '2020-12-24 18:53:32',
            ),
            7 => 
            array (
                'id' => 8,
                'user_id' => 20,
                'ssc_year' => NULL,
                'ssc_result' => NULL,
                'ssc_board_id' => NULL,
                'hsc_year' => NULL,
                'hsc_result' => NULL,
                'hsc_board_id' => NULL,
                'degree_year' => 2000,
                'degree_category_id' => 13,
                'uni' => 'university of barisal',
                'sub' => 'Bachelor of Arts',
                'degree_result' => 3.44,
                'created_at' => '2020-12-24 18:58:05',
                'updated_at' => '2020-12-24 19:02:31',
            ),
            8 => 
            array (
                'id' => 9,
                'user_id' => 21,
                'ssc_year' => NULL,
                'ssc_result' => NULL,
                'ssc_board_id' => NULL,
                'hsc_year' => NULL,
                'hsc_result' => NULL,
                'hsc_board_id' => NULL,
                'degree_year' => NULL,
                'degree_category_id' => NULL,
                'uni' => NULL,
                'sub' => NULL,
                'degree_result' => NULL,
                'created_at' => '2020-12-24 19:07:41',
                'updated_at' => '2020-12-24 19:07:41',
            ),
            9 => 
            array (
                'id' => 10,
                'user_id' => 22,
                'ssc_year' => NULL,
                'ssc_result' => NULL,
                'ssc_board_id' => NULL,
                'hsc_year' => NULL,
                'hsc_result' => NULL,
                'hsc_board_id' => NULL,
                'degree_year' => 2010,
                'degree_category_id' => 23,
                'uni' => 'Stamford University',
                'sub' => 'LL.M',
                'degree_result' => 3.56,
                'created_at' => '2020-12-24 19:30:20',
                'updated_at' => '2020-12-24 19:35:27',
            ),
            10 => 
            array (
                'id' => 11,
                'user_id' => 23,
                'ssc_year' => NULL,
                'ssc_result' => NULL,
                'ssc_board_id' => NULL,
                'hsc_year' => NULL,
                'hsc_result' => NULL,
                'hsc_board_id' => NULL,
                'degree_year' => NULL,
                'degree_category_id' => NULL,
                'uni' => NULL,
                'sub' => NULL,
                'degree_result' => NULL,
                'created_at' => '2020-12-25 07:06:11',
                'updated_at' => '2020-12-25 07:06:11',
            ),
            11 => 
            array (
                'id' => 12,
                'user_id' => 24,
                'ssc_year' => NULL,
                'ssc_result' => NULL,
                'ssc_board_id' => NULL,
                'hsc_year' => NULL,
                'hsc_result' => NULL,
                'hsc_board_id' => NULL,
                'degree_year' => NULL,
                'degree_category_id' => NULL,
                'uni' => NULL,
                'sub' => NULL,
                'degree_result' => NULL,
                'created_at' => '2020-12-25 07:29:14',
                'updated_at' => '2020-12-25 07:29:14',
            ),
            12 => 
            array (
                'id' => 13,
                'user_id' => 25,
                'ssc_year' => NULL,
                'ssc_result' => NULL,
                'ssc_board_id' => NULL,
                'hsc_year' => NULL,
                'hsc_result' => NULL,
                'hsc_board_id' => NULL,
                'degree_year' => NULL,
                'degree_category_id' => NULL,
                'uni' => NULL,
                'sub' => NULL,
                'degree_result' => NULL,
                'created_at' => '2020-12-25 07:33:50',
                'updated_at' => '2020-12-25 07:33:50',
            ),
            13 => 
            array (
                'id' => 14,
                'user_id' => 26,
                'ssc_year' => NULL,
                'ssc_result' => NULL,
                'ssc_board_id' => NULL,
                'hsc_year' => NULL,
                'hsc_result' => NULL,
                'hsc_board_id' => NULL,
                'degree_year' => NULL,
                'degree_category_id' => NULL,
                'uni' => NULL,
                'sub' => NULL,
                'degree_result' => NULL,
                'created_at' => '2020-12-25 08:00:46',
                'updated_at' => '2020-12-25 08:00:46',
            ),
            14 => 
            array (
                'id' => 15,
                'user_id' => 27,
                'ssc_year' => NULL,
                'ssc_result' => NULL,
                'ssc_board_id' => NULL,
                'hsc_year' => NULL,
                'hsc_result' => NULL,
                'hsc_board_id' => NULL,
                'degree_year' => NULL,
                'degree_category_id' => NULL,
                'uni' => NULL,
                'sub' => NULL,
                'degree_result' => NULL,
                'created_at' => '2020-12-25 08:04:53',
                'updated_at' => '2020-12-25 08:04:53',
            ),
            15 => 
            array (
                'id' => 16,
                'user_id' => 28,
                'ssc_year' => NULL,
                'ssc_result' => NULL,
                'ssc_board_id' => NULL,
                'hsc_year' => NULL,
                'hsc_result' => NULL,
                'hsc_board_id' => NULL,
                'degree_year' => NULL,
                'degree_category_id' => NULL,
                'uni' => NULL,
                'sub' => NULL,
                'degree_result' => NULL,
                'created_at' => '2020-12-25 08:12:45',
                'updated_at' => '2020-12-25 08:12:45',
            ),
            16 => 
            array (
                'id' => 17,
                'user_id' => 29,
                'ssc_year' => NULL,
                'ssc_result' => NULL,
                'ssc_board_id' => NULL,
                'hsc_year' => NULL,
                'hsc_result' => NULL,
                'hsc_board_id' => NULL,
                'degree_year' => NULL,
                'degree_category_id' => NULL,
                'uni' => NULL,
                'sub' => NULL,
                'degree_result' => NULL,
                'created_at' => '2020-12-25 08:53:57',
                'updated_at' => '2020-12-25 08:53:57',
            ),
            17 => 
            array (
                'id' => 18,
                'user_id' => 30,
                'ssc_year' => NULL,
                'ssc_result' => NULL,
                'ssc_board_id' => NULL,
                'hsc_year' => NULL,
                'hsc_result' => NULL,
                'hsc_board_id' => NULL,
                'degree_year' => NULL,
                'degree_category_id' => NULL,
                'uni' => NULL,
                'sub' => NULL,
                'degree_result' => NULL,
                'created_at' => '2020-12-25 09:02:22',
                'updated_at' => '2020-12-25 09:02:22',
            ),
        ));
        
        
    }
}